alert_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cnc.urls')),
]

cnc/urls.py
from django.urls import path

from .views import OperationAPIView, TechnicianAPIView, MachineAPIView, ResolveAlertAPIView, AlertAPIView, Dashboard

urlpatterns = [
    path('machines/', MachineAPIView.as_view()),
    path('technician/', TechnicianAPIView.as_view()),
    path('operation/', OperationAPIView.as_view()),
    path('alert/', AlertAPIView.as_view()),
    path('alert/resolve/<int:alert_id>/', ResolveAlertAPIView.as_view()),
    path('', Dashboard.as_view()),
]

cnc/models.py
from django.db import models

class Machine(models.Model):
    STATUS_CHOICES = [
        ('running', 'Running'),
        ('stopped', 'Stopped'),
    ]

    name = models.CharField(max_length=20, unique=True)
    machine_type = models.CharField(max_length=15)
    status = models.CharField(max_length=15, choices=STATUS_CHOICES, default='running')
    last_active = models.DateTimeField(auto_now=True)

class Technician(models.Model):
    name = models.CharField(max_length=100)
    phone = models.CharField(max_length=15)
    available = models.BooleanField(default=True)
    
class Operation(models.Model):
    machine = models.ForeignKey(Machine, on_delete=models.CASCADE)
    temperature = models.FloatField()
    vibration = models.FloatField()
    created_at = models.DateTimeField(auto_now_add=True)

class Alert(models.Model):
    SEVERITY = [
        (0, 'Low'),
        (1, 'High'),
    ]

    machine = models.ForeignKey(Machine, on_delete=models.CASCADE)
    technician = models.ForeignKey(Technician, on_delete=models.SET_NULL, null=True, blank=True )
    message = models.TextField()
    severity = models.CharField(max_length=10, choices=SEVERITY)
    created_at = models.DateTimeField(auto_now_add=True)
    resolved = models.BooleanField(default=False)
    resolved_at = models.DateTimeField(null=True, blank=True)

cnc/views.py
from django.shortcuts import render
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from .models import Machine, Technician, Alert
from django.utils import timezone
from .serializers import OperationSerializer, MachineSerializer, TechnicianSerializer, AlertSerializer
from .tasks import check_operations

class MachineAPIView(APIView):
    def get(self, request):
        machines = Machine.objects.all()
        serializer = MachineSerializer(machines, many=True)
        return Response(serializer.data)
     
    def post(self, request):
        serializer = MachineSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(
            {"message": "Machine created"},
            status=201
        )
    
class TechnicianAPIView(APIView):
    def get(self, request):
        techs = Technician.objects.all()
        serializer = TechnicianSerializer(techs, many=True)
        return Response(serializer.data)

    def post(self, request):
        serializer = TechnicianSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        tech = serializer.save()
        
        pending = Alert.objects.filter(technician=None, resolved=False ).order_by('-severity')
        for alert in pending:
            alert.technician = tech
            alert.save()

            tech.available = False
            tech.save()
            break

        return Response(
            {"message": "Technician created"},
            status=201
        )

class OperationAPIView(APIView):
    def post(self, request):
        serializer = OperationSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        operation = serializer.save()
        check_operations(operation.machine)
        return Response(
            {"message": "operation received"},
            status=status.HTTP_201_CREATED
        )

class ResolveAlertAPIView(APIView):
    def post(self, request, alert_id):
        try:
            alert = Alert.objects.get(id=alert_id)
            alert.resolved = True
            alert.resolved_at = timezone.now()
            tech = alert.technician
            alert.save()

            if tech:
                tech.available = True
                tech.save()

            alert.machine.status = "running"
            alert.machine.save()

            return Response({
                "message": "Alert Resolved"
            })

        except Alert.DoesNotExist:
            return Response({
                "error": "Alert Not Found"
            }, status=404)
        
class AlertAPIView(APIView):
    def get(self, request):
        alerts = Alert.objects.filter(resolved=False).order_by(
            '-severity',
            '-created_at'
        )
        serializer = AlertSerializer(alerts, many=True)
        return Response(serializer.data)

class Dashboard(APIView):
    def get(self, request):
        machines = Machine.objects.all()
        alerts = Alert.objects.filter(resolved=False).order_by('-severity')
        techs = Technician.objects.all()

        return render(request, 'dashboard.html', {
            "machines": machines,
            "alerts": alerts,
            "techs": techs
        })

cnc/templates/dashboard.html
<!DOCTYPE html>
<html>
<head>
    <title>Factory Monitor</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>

<h1>Factory Monitoring System</h1>
<div class="section">
    <h2>Machines</h2>

    <table>
        <tr>
            <th>Name</th>
            <th>Type</th>
            <th>Status</th>
        </tr>

        {% for m in machines %}
        <tr>
            <td>{{ m.name }}</td>
            <td>{{ m.machine_type }}</td>
            <td class="{{ m.status }}">
                {{ m.status }}
            </td>
        </tr>
        {% endfor %}
    </table>
</div>

<div class="section">
    <h2>Active Alerts</h2>
    <table>
        <tr>
            <th>Machine</th>
            <th>Message</th>
            <th>Severity</th>
            <th>Technician</th>
        </tr>

        {% for a in alerts %}
        <tr class="{{ a.severity }}">
            <td>{{ a.machine.name }}</td>
            <td>{{ a.message }}</td>
            <td>{{ a.get_severity_display }}</td>
            <td>{{ a.technician.name|default:"Not Assigned" }}</td>
        </tr>
        {% endfor %}
    </table>
</div>

<div class="section">
    <h2>Technicians</h2>
    <table>
        <tr>
            <th>Name</th>
            <th>Phone</th>
            <th>Status</th>
        </tr>   

        {% for t in techs %}
        <tr>
            <td>{{ t.name }}</td>
            <td>{{ t.phone }}</td>
            <td>
                {% if t.available %}
                    Free
                {% else %}
                    Busy
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </table>
</div>
</body>
</html>